name: Prompt
description: Prompt for Coding Agent
body:
  - type: dropdown
    id: school
    attributes:
      label: School
      options:
        - pca
        - scsa
  - type: textarea
    id: requirements
    attributes:
      label: Requirements